### ISSUE TITLE
Do I need to include my token?

### ISSUE THREAD

**Issue by SebastianHeyneman** [eskerda/slack-keep-presence#11]
I installed npm and then ran $ npm install slack-keep-presence

Do I need to include something else? Will it now work to prevent autoaway on slack?

Interestingly, how can I confirm that the autoaway is set up? Because any time I would go to check, it would trigger auto-away to disable anyway.

**Comment by eskerda** [comment]
> I installed npm and then ran $ npm install slack-keep-presence
> Do I need to include something else? Will it now work to prevent autoaway on slack?

Yes, you need a token. Please read https://github.com/eskerda/slack-keep-presence#usage

> Interestingly, how can I confirm that the autoaway is set up? Because any time I would go to check, it would trigger auto-away to disable anyway.

You can't, except by looking into the logging. Maybe ask a coworker ;)

**Comment by SebastianHeyneman** [comment]
I put in "slack-keep-presence -t xoxp-123123123123123” to terminal, but it
said -bash: slack-keep-presence: command not found


Also, clearly, 123123123123 isn’t the token. I put the real token for the
actual command.


-- 
Sebastian H. Wells
415.513.7629 <(415)%20513-7629> | LinkedIn
<https://www.linkedin.com/in/sebastianhwells/>
Business Analyst @ BuildingConnected <http://www.buildingconnected.com>

On Oct 14, 2017 at 11:59 PM, eskerda <notifications@github.com> wrote:


I installed npm and then ran $ npm install slack-keep-presence
Do I need to include something else? Will it now work to prevent autoaway
on slack?

Yes, you need a token. Please read
https://github.com/eskerda/slack-keep-presence#usage

Interestingly, how can I confirm that the autoaway is set up? Because any
time I would go to check, it would trigger auto-away to disable anyway.

You can't, except by looking into the logging. Maybe ask a coworker ;)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/eskerda/slack-keep-presence/issues/11#issuecomment-336690994>,
or mute the thread

**Comment by eskerda** [comment]
From the readme

> Following assumes $HOME/node_modules/.bin is present on your $PATH

So, either do that, or execute it as `$HOME/node_modules/.bin/slack-keep-presence`
