### ISSUE TITLE
Confirmed:  August 2018 , this is NOT working as Slack has retired this API endpoint. This one works: https://libraries.io/rubygems/slack-keep-presence

### ISSUE THREAD

**Issue by prog1113** [eskerda/slack-keep-presence#13]
Confirmed:  To save you time,  as of **August 2018** , this is **no longer working** as Slack has retired the API endpoint used by this one.  

I have tried this fork of 'slack-keep-presence' by Joshfng  and it works as it is using an updated Slack API endpoint. It is at: [https://libraries.io/rubygems/slack-keep-presence](https://libraries.io/rubygems/slack-keep-presence)

**Comment by jonschtote** [comment]
> Confirmed: To save you time, as of **August 2018** , this is **no longer working** as Slack has retired the API endpoint used by this one.
> 
> I have tried this fork of 'slack-keep-presence' by Joshfng and it works as it is using an updated Slack API endpoint. It is at: https://github.com/joshfng/slack-keep-presence

Its 404 now... :(

**Comment by prog1113** [comment]
Hi jonschtote, 

Please see [https://libraries.io/rubygems/slack-keep-presence](https://libraries.io/rubygems/slack-keep-presence )

Just sharing my research:
Using "mouse jiggler" or any software that simulates mouse or keyboard movement in your computer will NOT keep your Slack status as "active". I am using Slack Desktop Client in Mac OS Mojave with the Mac Jiggler App by Stick Software / Ben Haller, and apparently Slack will mark you away after 30 minutes.  As of **November 2018** : only if you interact within Slack Desktop client once every 30 minutes, your status will stay "active".  

I immensely hate this design decision by Slack. How can one focus and do creative deep work with such a _short attention span_?

After a few days' investigation, I found that Slack retired the "users.setPresence" API. Hence, this one is not working despite being first result  in Google search.

So if you are working from home or remotely or even in the office, your best bet is to run the Ruby gem [https://libraries.io/rubygems/slack-keep-presence](https://libraries.io/rubygems/slack-keep-presence) .  Just to confirm:  I have methodically verified this one and it works! It is a little hack in setting the user's presence to active by creating a new fresh websocket connection to Slack .

My motivation is that:  I work remotely and my micro-manager complained that I was rarely available. He was partly true, as I like to read, take a nap, take a walk, or watch films in my home  after my work is done. 

Read the book "It doesn't have to be crazy at work" by DHH and Jason Fried (Basecamp).

**Comment by eskerda** [comment]
@prog1113 I agree and this is exactly why I created this on the first place. I do not use slack anymore so I have no interest at the moment to keep this software up to date. I have added a disclaimer on the readme with a link to the rubygem you mentioned.

Thanks!

**Comment by jonschtote** [comment]
> Hi jonschtote,
>... SNIP

Hello, thanks for the quick replies!

I thought this was dead honestly and I wanted to save others from what I felt was a dead end.

I found this site and gave it my token.

I am having similar issues, I am being held accountable to the little status icon on slack despite whether I am working or not, it is frustrating to know I am working but a piece of software that a dev clearly doesnt want to change is dictating my attendance and performance for my living and support of my family.

https://slackpresence.com works easy and has a super simple setup. Free and if you think your work will be wise of 24/7 green you can pay a pittance to schedule it

**Comment by carrot69** [comment]
For those who can't make this or another solution work, I just made this simple program, the only thing that it does is to move the mouse cursor if it detects that you are away, tricking any program to think that you are still working on your computer:

Install it with snap:

`sudo snap install keep-presence`   



More info here: https://github.com/carrot69/keep-presence/
